- type: mobStateParams
  id: AliveDefault
  moving: true
  talking: true
  emoting: true
  throwing: true
  pickingUp: true
  pulling: true
  attacking: true
  using: true
  pointing: true 
  isConscious: true
  canEquipSelf: true
  canUnequipSelf: true
  canEquipOther: true
  canUnequipOther: true
  forceDown: false
  incapacitated: false
  canBreathe: true

- type: mobStateParams
  id: SoftCriticalDefault
  moving: true
  talking: true
  emoting: true
  throwing: false
  pickingUp: false
  pulling: false
  attacking: false
  using: true
  pointing: true 
  isConscious: true
  canEquipSelf: false
  canUnequipSelf: true
  canEquipOther: false
  canUnequipOther: false
  forceDown: true
  incapacitated: true
  canBreathe: true
  oxyDamageOverlay: 0.75
  strippingTimeMultiplier: 0.5

- type: mobStateParams
  id: CriticalDefault
  moving: false
  talking: false
  emoting: false
  throwing: false
  pickingUp: false
  pulling: false
  attacking: false
  using: false
  pointing: false 
  isConscious: false
  canEquipSelf: false
  canUnequipSelf: false
  canEquipOther: false
  canUnequipOther: false
  forceDown: true
  incapacitated: true
  canBreathe: false
  oxyDamageOverlay: 1
  strippingTimeMultiplier: 0.33

- type: mobStateParams
  id: DeadDefault
  moving: false
  talking: false
  emoting: false
  throwing: false
  pickingUp: false
  pulling: false
  attacking: false
  using: false
  pointing: false 
  isConscious: false
  canEquipSelf: false
  canUnequipSelf: false
  canEquipOther: false
  canUnequipOther: false
  forceDown: true
  incapacitated: true
  canBreathe: false
  oxyDamageOverlay: 0
  strippingTimeMultiplier: 0.33
